[profile.default]
src = "src"
test = "test"
libs = ["lib"]
out = "out"
remappings = []
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
bracket_spacing = true
multiline_func_header = "attributes_first"
